###
GET http://localhost:9000/api HTTP/1.1


###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "title": "Alice in The Wonder Land",
  "author": "Lewis Carrol",
  "edition": 5
}

###
DELETE http://localhost:9000/api/7 HTTP/1.1

###
PUT http://localhost:9000/api/2 HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "title": "The Chronicles of Narnia Part II",
  "author": "C.S. Lewis",
  "edition": 8
}
